<?php

use App\City;
use Illuminate\Database\Seeder;


class CitysSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create([ "id_departament"=>1, "name"=>"-"]);
        City::create([ "id_departament"=>2, "name"=>"LETICIA"]);
        City::create([ "id_departament"=>2, "name"=>"PUERTO NARIÑO"]);
        City::create([ "id_departament"=>3, "name"=>"ABEJORRAL"]);
        City::create([ "id_departament"=>3, "name"=>"ABRIAQUÍ"]);
        City::create([ "id_departament"=>3, "name"=>"ALEJANDRÍA"]);
        City::create([ "id_departament"=>3, "name"=>"AMAGÁ"]);
        City::create([ "id_departament"=>3, "name"=>"AMALFI"]);
        City::create([ "id_departament"=>3, "name"=>"ANDES"]);
        City::create([ "id_departament"=>3, "name"=>"ANGELÓPOLIS"]);
        City::create([ "id_departament"=>3, "name"=>"ANGOSTURA"]);
        City::create([ "id_departament"=>3, "name"=>"ANORÍ"]);
        City::create([ "id_departament"=>3, "name"=>"ANZÁ"]);
        City::create([ "id_departament"=>3, "name"=>"APARTADÓ"]);
        City::create([ "id_departament"=>3, "name"=>"ARBOLETES"]);
        City::create([ "id_departament"=>3, "name"=>"ARGELIA"]);
        City::create([ "id_departament"=>3, "name"=>"ARMENIA"]);
        City::create([ "id_departament"=>3, "name"=>"BARBOSA"]);
        City::create([ "id_departament"=>3, "name"=>"BELLO"]);
        City::create([ "id_departament"=>3, "name"=>"BELMIRA"]);
        City::create([ "id_departament"=>3, "name"=>"BETANIA"]);
        City::create([ "id_departament"=>3, "name"=>"BETULIA"]);
        City::create([ "id_departament"=>3, "name"=>"BRICEÑO"]);
        City::create([ "id_departament"=>3, "name"=>"BURITICÁ"]);
        City::create([ "id_departament"=>3, "name"=>"CACERES"]);
        City::create([ "id_departament"=>3, "name"=>"CAICEDO"]);
        City::create([ "id_departament"=>3, "name"=>"CALDAS"]);
        City::create([ "id_departament"=>3, "name"=>"CAMPAMENTO"]);
        City::create([ "id_departament"=>3, "name"=>"CAÑASGORDAS"]);
        City::create([ "id_departament"=>3, "name"=>"CARACOLÍ"]);
        City::create([ "id_departament"=>3, "name"=>"CARAMANTA"]);
        City::create([ "id_departament"=>3, "name"=>"CAREPA"]);
        City::create([ "id_departament"=>3, "name"=>"CAROLINA DEL PRÍNCIPE"]);
        City::create([ "id_departament"=>3, "name"=>"CAUCASIA"]);
        City::create([ "id_departament"=>3, "name"=>"CHIGORODÓ"]);
        City::create([ "id_departament"=>3, "name"=>"CISNEROS"]);
        City::create([ "id_departament"=>3, "name"=>"CIUDAD BOLÍVAR"]);
        City::create([ "id_departament"=>3, "name"=>"COCORNÁ"]);
        City::create([ "id_departament"=>3, "name"=>"CONCEPCIÓN"]);
        City::create([ "id_departament"=>3, "name"=>"CONCORDIA"]);
        City::create([ "id_departament"=>3, "name"=>"COPACABANA"]);
        City::create([ "id_departament"=>3, "name"=>"DABEIBA"]);
        City::create([ "id_departament"=>3, "name"=>"DONMATÍAS"]);
        City::create([ "id_departament"=>3, "name"=>"EBÉJICO"]);
        City::create([ "id_departament"=>3, "name"=>"EL BAGRE"]);
        City::create([ "id_departament"=>3, "name"=>"EL CARMEN DE VIBORAL"]);
        City::create([ "id_departament"=>3, "name"=>"EL PEÑOL"]);
        City::create([ "id_departament"=>3, "name"=>"EL RETIRO"]);
        City::create([ "id_departament"=>3, "name"=>"EL SANTUARIO"]);
        City::create([ "id_departament"=>3, "name"=>"ENTRERRÍOS"]);
        City::create([ "id_departament"=>3, "name"=>"ENVIGADO"]);
        City::create([ "id_departament"=>3, "name"=>"FREDONIA"]);
        City::create([ "id_departament"=>3, "name"=>"FRONTINO"]);
        City::create([ "id_departament"=>3, "name"=>"GIRALDO"]);
        City::create([ "id_departament"=>3, "name"=>"GIRARDOTA"]);
        City::create([ "id_departament"=>3, "name"=>"GÓMEZ PLATA"]);
        City::create([ "id_departament"=>3, "name"=>"GRANADA"]);
        City::create([ "id_departament"=>3, "name"=>"GUADALUPE"]);
        City::create([ "id_departament"=>3, "name"=>"GUARNE"]);
        City::create([ "id_departament"=>3, "name"=>"GUATAPÉ"]);
        City::create([ "id_departament"=>3, "name"=>"HELICONIA"]);
        City::create([ "id_departament"=>3, "name"=>"HISPANIA"]);
        City::create([ "id_departament"=>3, "name"=>"ITAGÜÍ"]);
        City::create([ "id_departament"=>3, "name"=>"ITUANGO"]);
        City::create([ "id_departament"=>3, "name"=>"JARDÍN"]);
        City::create([ "id_departament"=>3, "name"=>"JERICÓ"]);
        City::create([ "id_departament"=>3, "name"=>"LA CEJA"]);
        City::create([ "id_departament"=>3, "name"=>"LA ESTRELLA"]);
        City::create([ "id_departament"=>3, "name"=>"LA PINTADA"]);
        City::create([ "id_departament"=>3, "name"=>"LA UNIÓN"]);
        City::create([ "id_departament"=>3, "name"=>"LIBORINA"]);
        City::create([ "id_departament"=>3, "name"=>"MACEO"]);
        City::create([ "id_departament"=>3, "name"=>"MARINILLA"]);
        City::create([ "id_departament"=>3, "name"=>"MEDELLÍN"]);
        City::create([ "id_departament"=>3, "name"=>"MONTEBELLO"]);
        City::create([ "id_departament"=>3, "name"=>"MURINDÓ"]);
        City::create([ "id_departament"=>3, "name"=>"MUTATÁ"]);
        City::create([ "id_departament"=>3, "name"=>"NARIÑO"]);
        City::create([ "id_departament"=>3, "name"=>"NECHÍ"]);
        City::create([ "id_departament"=>3, "name"=>"NECOCLÍ"]);
        City::create([ "id_departament"=>3, "name"=>"OLAYA"]);
        City::create([ "id_departament"=>3, "name"=>"PEQUE"]);
        City::create([ "id_departament"=>3, "name"=>"PUEBLORRICO"]);
        City::create([ "id_departament"=>3, "name"=>"PUERTO BERRÍO"]);
        City::create([ "id_departament"=>3, "name"=>"PUERTO NARE"]);
        City::create([ "id_departament"=>3, "name"=>"PUERTO TRIUNFO"]);
        City::create([ "id_departament"=>3, "name"=>"REMEDIOS"]);
        City::create([ "id_departament"=>3, "name"=>"RIONEGRO"]);
        City::create([ "id_departament"=>3, "name"=>"SABANALARGA"]);
        City::create([ "id_departament"=>3, "name"=>"SABANETA"]);
        City::create([ "id_departament"=>3, "name"=>"SALGAR"]);
        City::create([ "id_departament"=>3, "name"=>"SAN ANDRÉS DE CUERQUIA"]);
        City::create([ "id_departament"=>3, "name"=>"SAN CARLOS"]);
        City::create([ "id_departament"=>3, "name"=>"SAN FRANCISCO"]);
        City::create([ "id_departament"=>3, "name"=>"SAN JERÓNIMO"]);
        City::create([ "id_departament"=>3, "name"=>"SAN JOSÉ DE LA MONTAÑA"]);
        City::create([ "id_departament"=>3, "name"=>"SAN JUAN DE URABÁ"]);
        City::create([ "id_departament"=>3, "name"=>"SAN LUIS"]);
        City::create([ "id_departament"=>3, "name"=>"SAN PEDRO DE LOS MILAGROS"]);
        City::create([ "id_departament"=>3, "name"=>"SAN PEDRO DE URABÁ"]);
        City::create([ "id_departament"=>3, "name"=>"SAN RAFAEL"]);
        City::create([ "id_departament"=>3, "name"=>"SAN ROQUE"]);
        City::create([ "id_departament"=>3, "name"=>"SAN VICENTE"]);
        City::create([ "id_departament"=>3, "name"=>"SANTA BÁRBARA"]);
        City::create([ "id_departament"=>3, "name"=>"SANTA FE DE ANTIOQUIA"]);
        City::create([ "id_departament"=>3, "name"=>"SANTA ROSA DE OSOS"]);
        City::create([ "id_departament"=>3, "name"=>"SANTO DOMINGO"]);
        City::create([ "id_departament"=>3, "name"=>"SEGOVIA"]);
        City::create([ "id_departament"=>3, "name"=>"SONSÓN"]);
        City::create([ "id_departament"=>3, "name"=>"SOPETRÁN"]);
        City::create([ "id_departament"=>3, "name"=>"TÁMESIS"]);
        City::create([ "id_departament"=>3, "name"=>"TARAZÁ"]);
        City::create([ "id_departament"=>3, "name"=>"TARSO"]);
        City::create([ "id_departament"=>3, "name"=>"TITIRIBÍ"]);
        City::create([ "id_departament"=>3, "name"=>"TOLEDO"]);
        City::create([ "id_departament"=>3, "name"=>"TURBO"]);
        City::create([ "id_departament"=>3, "name"=>"URAMITA"]);
        City::create([ "id_departament"=>3, "name"=>"URRAO"]);
        City::create([ "id_departament"=>3, "name"=>"VALDIVIA"]);
        City::create([ "id_departament"=>3, "name"=>"VALPARAÍSO"]);
        City::create([ "id_departament"=>3, "name"=>"VEGACHÍ"]);
        City::create([ "id_departament"=>3, "name"=>"VENECIA"]);
        City::create([ "id_departament"=>3, "name"=>"VIGÍA DEL FUERTE"]);
        City::create([ "id_departament"=>3, "name"=>"YALÍ"]);
        City::create([ "id_departament"=>3, "name"=>"YARUMAL"]);
        City::create([ "id_departament"=>3, "name"=>"YOLOMBÓ"]);
        City::create([ "id_departament"=>3, "name"=>"YONDÓ"]);
        City::create([ "id_departament"=>3, "name"=>"ZARAGOZA"]);
        City::create([ "id_departament"=>4, "name"=>"ARAUCA"]);
        City::create([ "id_departament"=>4, "name"=>"ARAUQUITA"]);
        City::create([ "id_departament"=>4, "name"=>"CRAVO NORTE"]);
        City::create([ "id_departament"=>4, "name"=>"FORTUL"]);
        City::create([ "id_departament"=>4, "name"=>"PUERTO RONDÓN"]);
        City::create([ "id_departament"=>4, "name"=>"SARAVENA"]);
        City::create([ "id_departament"=>4, "name"=>"TAME"]);
        City::create([ "id_departament"=>5, "name"=>"BARANOA"]);
        City::create([ "id_departament"=>5, "name"=>"BARRANQUILLA"]);
        City::create([ "id_departament"=>5, "name"=>"CAMPO DE LA CRUZ"]);
        City::create([ "id_departament"=>5, "name"=>"CANDELARIA"]);
        City::create([ "id_departament"=>5, "name"=>"GALAPA"]);
        City::create([ "id_departament"=>5, "name"=>"JUAN DE ACOSTA"]);
        City::create([ "id_departament"=>5, "name"=>"LURUACO"]);
        City::create([ "id_departament"=>5, "name"=>"MALAMBO"]);
        City::create([ "id_departament"=>5, "name"=>"MANATÍ"]);
        City::create([ "id_departament"=>5, "name"=>"PALMAR DE VARELA"]);
        City::create([ "id_departament"=>5, "name"=>"PIOJÓ"]);
        City::create([ "id_departament"=>5, "name"=>"POLONUEVO"]);
        City::create([ "id_departament"=>5, "name"=>"PONEDERA"]);
        City::create([ "id_departament"=>5, "name"=>"PUERTO COLOMBIA"]);
        City::create([ "id_departament"=>5, "name"=>"REPELÓN"]);
        City::create([ "id_departament"=>5, "name"=>"SABANAGRANDE"]);
        City::create([ "id_departament"=>5, "name"=>"SABANALARGA"]);
        City::create([ "id_departament"=>5, "name"=>"SANTA LUCÍA"]);
        City::create([ "id_departament"=>5, "name"=>"SANTO TOMÁS"]);
        City::create([ "id_departament"=>5, "name"=>"SOLEDAD"]);
        City::create([ "id_departament"=>5, "name"=>"SUAN"]);
        City::create([ "id_departament"=>5, "name"=>"TUBARÁ"]);
        City::create([ "id_departament"=>5, "name"=>"USIACURÍ"]);
        City::create([ "id_departament"=>6, "name"=>"ACHÍ"]);
        City::create([ "id_departament"=>6, "name"=>"ALTOS DEL ROSARIO"]);
        City::create([ "id_departament"=>6, "name"=>"ARENAL"]);
        City::create([ "id_departament"=>6, "name"=>"ARJONA"]);
        City::create([ "id_departament"=>6, "name"=>"ARROYOHONDO"]);
        City::create([ "id_departament"=>6, "name"=>"BARRANCO DE LOBA"]);
        City::create([ "id_departament"=>6, "name"=>"CALAMAR"]);
        City::create([ "id_departament"=>6, "name"=>"CANTAGALLO"]);
        City::create([ "id_departament"=>6, "name"=>"CARTAGENA DE INDIAS"]);
        City::create([ "id_departament"=>6, "name"=>"CICUCO"]);
        City::create([ "id_departament"=>6, "name"=>"CLEMENCIA"]);
        City::create([ "id_departament"=>6, "name"=>"CÓRDOBA"]);
        City::create([ "id_departament"=>6, "name"=>"EL CARMEN DE BOLÍVAR"]);
        City::create([ "id_departament"=>6, "name"=>"EL GUAMO"]);
        City::create([ "id_departament"=>6, "name"=>"EL PEÑÓN"]);
        City::create([ "id_departament"=>6, "name"=>"HATILLO DE LOBA"]);
        City::create([ "id_departament"=>6, "name"=>"MAGANGUÉ"]);
        City::create([ "id_departament"=>6, "name"=>"MAHATES"]);
        City::create([ "id_departament"=>6, "name"=>"MARGARITA"]);
        City::create([ "id_departament"=>6, "name"=>"MARÍA LA BAJA"]);
        City::create([ "id_departament"=>6, "name"=>"MONTECRISTO"]);
        City::create([ "id_departament"=>6, "name"=>"MORALES"]);
        City::create([ "id_departament"=>6, "name"=>"NOROSÍ"]);
        City::create([ "id_departament"=>6, "name"=>"PINILLOS"]);
        City::create([ "id_departament"=>6, "name"=>"REGIDOR"]);
        City::create([ "id_departament"=>6, "name"=>"RÍO VIEJO"]);
        City::create([ "id_departament"=>6, "name"=>"SAN CRISTÓBAL"]);
        City::create([ "id_departament"=>6, "name"=>"SAN ESTANISLAO"]);
        City::create([ "id_departament"=>6, "name"=>"SAN FERNANDO"]);
        City::create([ "id_departament"=>6, "name"=>"SAN JACINTO"]);
        City::create([ "id_departament"=>6, "name"=>"SAN JACINTO DEL CAUCA"]);
        City::create([ "id_departament"=>6, "name"=>"SAN JUAN NEPOMUCENO"]);
        City::create([ "id_departament"=>6, "name"=>"SAN MARTÍN DE LOBA"]);
        City::create([ "id_departament"=>6, "name"=>"SAN PABLO"]);
        City::create([ "id_departament"=>6, "name"=>"SANTA CATALINA"]);
        City::create([ "id_departament"=>6, "name"=>"SANTA CRUZ DE MOMPOX"]);
        City::create([ "id_departament"=>6, "name"=>"SANTA ROSA"]);
        City::create([ "id_departament"=>6, "name"=>"SANTA ROSA DEL SUR"]);
        City::create([ "id_departament"=>6, "name"=>"SIMITÍ"]);
        City::create([ "id_departament"=>6, "name"=>"SOPLAVIENTO"]);
        City::create([ "id_departament"=>6, "name"=>"TALAIGUA NUEVO"]);
        City::create([ "id_departament"=>6, "name"=>"TIQUISIO"]);
        City::create([ "id_departament"=>6, "name"=>"TURBACO"]);
        City::create([ "id_departament"=>6, "name"=>"TURBANÁ"]);
        City::create([ "id_departament"=>6, "name"=>"VILLANUEVA"]);
        City::create([ "id_departament"=>6, "name"=>"ZAMBRANO"]);
        City::create([ "id_departament"=>7, "name"=>"ALMEIDA"]);
        City::create([ "id_departament"=>7, "name"=>"AQUITANIA"]);
        City::create([ "id_departament"=>7, "name"=>"ARCABUCO"]);
        City::create([ "id_departament"=>7, "name"=>"BELÉN"]);
        City::create([ "id_departament"=>7, "name"=>"BERBEO"]);
        City::create([ "id_departament"=>7, "name"=>"BETÉITIVA"]);
        City::create([ "id_departament"=>7, "name"=>"BOAVITA"]);
        City::create([ "id_departament"=>7, "name"=>"BOYACÁ"]);
        City::create([ "id_departament"=>7, "name"=>"BRICEÑO"]);
        City::create([ "id_departament"=>7, "name"=>"BUENAVISTA"]);
        City::create([ "id_departament"=>7, "name"=>"BUSBANZÁ"]);
        City::create([ "id_departament"=>7, "name"=>"CALDAS"]);
        City::create([ "id_departament"=>7, "name"=>"CAMPOHERMOSO"]);
        City::create([ "id_departament"=>7, "name"=>"CERINZA"]);
        City::create([ "id_departament"=>7, "name"=>"CHINAVITA"]);
        City::create([ "id_departament"=>7, "name"=>"CHIQUINQUIRÁ"]);
        City::create([ "id_departament"=>7, "name"=>"CHÍQUIZA"]);
        City::create([ "id_departament"=>7, "name"=>"CHISCAS"]);
        City::create([ "id_departament"=>7, "name"=>"CHITA"]);
        City::create([ "id_departament"=>7, "name"=>"CHITARAQUE"]);
        City::create([ "id_departament"=>7, "name"=>"CHIVATÁ"]);
        City::create([ "id_departament"=>7, "name"=>"CHIVOR"]);
        City::create([ "id_departament"=>7, "name"=>"CIÉNEGA"]);
        City::create([ "id_departament"=>7, "name"=>"CÓMBITA"]);
        City::create([ "id_departament"=>7, "name"=>"COPER"]);
        City::create([ "id_departament"=>7, "name"=>"CORRALES"]);
        City::create([ "id_departament"=>7, "name"=>"COVARACHÍA"]);
        City::create([ "id_departament"=>7, "name"=>"CUBARÁ"]);
        City::create([ "id_departament"=>7, "name"=>"CUCAITA"]);
        City::create([ "id_departament"=>7, "name"=>"CUÍTIVA"]);
        City::create([ "id_departament"=>7, "name"=>"DUITAMA"]);
        City::create([ "id_departament"=>7, "name"=>"EL COCUY"]);
        City::create([ "id_departament"=>7, "name"=>"EL ESPINO"]);
        City::create([ "id_departament"=>7, "name"=>"FIRAVITOBA"]);
        City::create([ "id_departament"=>7, "name"=>"FLORESTA"]);
        City::create([ "id_departament"=>7, "name"=>"GACHANTIVÁ"]);
        City::create([ "id_departament"=>7, "name"=>"GÁMEZA"]);
        City::create([ "id_departament"=>7, "name"=>"GARAGOA"]);
        City::create([ "id_departament"=>7, "name"=>"GUACAMAYAS"]);
        City::create([ "id_departament"=>7, "name"=>"GUATEQUE"]);
        City::create([ "id_departament"=>7, "name"=>"GUAYATÁ"]);
        City::create([ "id_departament"=>7, "name"=>"GÜICÁN"]);
        City::create([ "id_departament"=>7, "name"=>"IZA"]);
        City::create([ "id_departament"=>7, "name"=>"JENESANO"]);
        City::create([ "id_departament"=>7, "name"=>"JERICÓ"]);
        City::create([ "id_departament"=>7, "name"=>"LA CAPILLA"]);
        City::create([ "id_departament"=>7, "name"=>"LA UVITA"]);
        City::create([ "id_departament"=>7, "name"=>"LA VICTORIA"]);
        City::create([ "id_departament"=>7, "name"=>"LABRANZAGRANDE"]);
        City::create([ "id_departament"=>7, "name"=>"MACANAL"]);
        City::create([ "id_departament"=>7, "name"=>"MARIPÍ"]);
        City::create([ "id_departament"=>7, "name"=>"MIRAFLORES"]);
        City::create([ "id_departament"=>7, "name"=>"MONGUA"]);
        City::create([ "id_departament"=>7, "name"=>"MONGUÍ"]);
        City::create([ "id_departament"=>7, "name"=>"MONIQUIRÁ"]);
        City::create([ "id_departament"=>7, "name"=>"MOTAVITA"]);
        City::create([ "id_departament"=>7, "name"=>"MUZO"]);
        City::create([ "id_departament"=>7, "name"=>"NOBSA"]);
        City::create([ "id_departament"=>7, "name"=>"NUEVO COLÓN"]);
        City::create([ "id_departament"=>7, "name"=>"OICATÁ"]);
        City::create([ "id_departament"=>7, "name"=>"OTANCHE"]);
        City::create([ "id_departament"=>7, "name"=>"PACHAVITA"]);
        City::create([ "id_departament"=>7, "name"=>"PÁEZ"]);
        City::create([ "id_departament"=>7, "name"=>"PAIPA"]);
        City::create([ "id_departament"=>7, "name"=>"PAJARITO"]);
        City::create([ "id_departament"=>7, "name"=>"PANQUEBA"]);
        City::create([ "id_departament"=>7, "name"=>"PAUNA"]);
        City::create([ "id_departament"=>7, "name"=>"PAYA"]);
        City::create([ "id_departament"=>7, "name"=>"PAZ DE RÍO"]);
        City::create([ "id_departament"=>7, "name"=>"PESCA"]);
        City::create([ "id_departament"=>7, "name"=>"PISBA"]);
        City::create([ "id_departament"=>7, "name"=>"PUERTO BOYACÁ"]);
        City::create([ "id_departament"=>7, "name"=>"QUÍPAMA"]);
        City::create([ "id_departament"=>7, "name"=>"RAMIRIQUÍ"]);
        City::create([ "id_departament"=>7, "name"=>"RÁQUIRA"]);
        City::create([ "id_departament"=>7, "name"=>"RONDÓN"]);
        City::create([ "id_departament"=>7, "name"=>"SABOYÁ"]);
        City::create([ "id_departament"=>7, "name"=>"SÁCHICA"]);
        City::create([ "id_departament"=>7, "name"=>"SAMACÁ"]);
        City::create([ "id_departament"=>7, "name"=>"SAN EDUARDO"]);
        City::create([ "id_departament"=>7, "name"=>"SAN JOSÉ DE PARE"]);
        City::create([ "id_departament"=>7, "name"=>"SAN LUIS DE GACENO"]);
        City::create([ "id_departament"=>7, "name"=>"SAN MATEO"]);
        City::create([ "id_departament"=>7, "name"=>"SAN MIGUEL DE SEMA"]);
        City::create([ "id_departament"=>7, "name"=>"SAN PABLO DE BORBUR"]);
        City::create([ "id_departament"=>7, "name"=>"SANTA MARÍA"]);
        City::create([ "id_departament"=>7, "name"=>"SANTA ROSA DE VITERBO"]);
        City::create([ "id_departament"=>7, "name"=>"SANTA SOFÍA"]);
        City::create([ "id_departament"=>7, "name"=>"SANTANA"]);
        City::create([ "id_departament"=>7, "name"=>"SATIVANORTE"]);
        City::create([ "id_departament"=>7, "name"=>"SATIVASUR"]);
        City::create([ "id_departament"=>7, "name"=>"SIACHOQUE"]);
        City::create([ "id_departament"=>7, "name"=>"SOATÁ"]);
        City::create([ "id_departament"=>7, "name"=>"SOCHA"]);
        City::create([ "id_departament"=>7, "name"=>"SOCOTÁ"]);
        City::create([ "id_departament"=>7, "name"=>"SOGAMOSO"]);
        City::create([ "id_departament"=>7, "name"=>"SOMONDOCO"]);
        City::create([ "id_departament"=>7, "name"=>"SORA"]);
        City::create([ "id_departament"=>7, "name"=>"SORACÁ"]);
        City::create([ "id_departament"=>7, "name"=>"SOTAQUIRÁ"]);
        City::create([ "id_departament"=>7, "name"=>"SUSACÓN"]);
        City::create([ "id_departament"=>7, "name"=>"SUTAMARCHÁN"]);
        City::create([ "id_departament"=>7, "name"=>"SUTATENZA"]);
        City::create([ "id_departament"=>7, "name"=>"TASCO"]);
        City::create([ "id_departament"=>7, "name"=>"TENZA"]);
        City::create([ "id_departament"=>7, "name"=>"TIBANÁ"]);
        City::create([ "id_departament"=>7, "name"=>"TIBASOSA"]);
        City::create([ "id_departament"=>7, "name"=>"TINJACÁ"]);
        City::create([ "id_departament"=>7, "name"=>"TIPACOQUE"]);
        City::create([ "id_departament"=>7, "name"=>"TOCA"]);
        City::create([ "id_departament"=>7, "name"=>"TOGÜÍ"]);
        City::create([ "id_departament"=>7, "name"=>"TÓPAGA"]);
        City::create([ "id_departament"=>7, "name"=>"TOTA"]);
        City::create([ "id_departament"=>7, "name"=>"TUNJA"]);
        City::create([ "id_departament"=>7, "name"=>"TUNUNGUÁ"]);
        City::create([ "id_departament"=>7, "name"=>"TURMEQUÉ"]);
        City::create([ "id_departament"=>7, "name"=>"TUTA"]);
        City::create([ "id_departament"=>7, "name"=>"TUTAZÁ"]);
        City::create([ "id_departament"=>7, "name"=>"ÚMBITA"]);
        City::create([ "id_departament"=>7, "name"=>"VENTAQUEMADA"]);
        City::create([ "id_departament"=>7, "name"=>"VILLA DE LEYVA"]);
        City::create([ "id_departament"=>7, "name"=>"VIRACACHÁ"]);
        City::create([ "id_departament"=>7, "name"=>"ZETAQUIRA"]);
        City::create([ "id_departament"=>8, "name"=>"AGUADAS"]);
        City::create([ "id_departament"=>8, "name"=>"ANSERMA"]);
        City::create([ "id_departament"=>8, "name"=>"ARANZAZU"]);
        City::create([ "id_departament"=>8, "name"=>"BELALCÁZAR"]);
        City::create([ "id_departament"=>8, "name"=>"CHINCHINÁ"]);
        City::create([ "id_departament"=>8, "name"=>"FILADELFIA"]);
        City::create([ "id_departament"=>8, "name"=>"LA DORADA"]);
        City::create([ "id_departament"=>8, "name"=>"LA MERCED"]);
        City::create([ "id_departament"=>8, "name"=>"MANIZALES"]);
        City::create([ "id_departament"=>8, "name"=>"MANZANARES"]);
        City::create([ "id_departament"=>8, "name"=>"MARMATO"]);
        City::create([ "id_departament"=>8, "name"=>"MARQUETALIA"]);
        City::create([ "id_departament"=>8, "name"=>"MARULANDA"]);
        City::create([ "id_departament"=>8, "name"=>"NEIRA"]);
        City::create([ "id_departament"=>8, "name"=>"NORCASIA"]);
        City::create([ "id_departament"=>8, "name"=>"PÁCORA"]);
        City::create([ "id_departament"=>8, "name"=>"PALESTINA"]);
        City::create([ "id_departament"=>8, "name"=>"PENSILVANIA"]);
        City::create([ "id_departament"=>8, "name"=>"RIOSUCIO"]);
        City::create([ "id_departament"=>8, "name"=>"RISARALDA"]);
        City::create([ "id_departament"=>8, "name"=>"SALAMINA"]);
        City::create([ "id_departament"=>8, "name"=>"SAMANÁ"]);
        City::create([ "id_departament"=>8, "name"=>"SAN JOSÉ"]);
        City::create([ "id_departament"=>8, "name"=>"SUPÍA"]);
        City::create([ "id_departament"=>8, "name"=>"VICTORIA"]);
        City::create([ "id_departament"=>8, "name"=>"VILLAMARÍA"]);
        City::create([ "id_departament"=>8, "name"=>"VITERBO"]);
        City::create([ "id_departament"=>9, "name"=>"ALBANIA"]);
        City::create([ "id_departament"=>9, "name"=>"BELÉN DE LOS ANDAQUÍES"]);
        City::create([ "id_departament"=>9, "name"=>"CARTAGENA DEL CHAIRÁ"]);
        City::create([ "id_departament"=>9, "name"=>"CURILLO"]);
        City::create([ "id_departament"=>9, "name"=>"EL DONCELLO"]);
        City::create([ "id_departament"=>9, "name"=>"EL PAUJIL"]);
        City::create([ "id_departament"=>9, "name"=>"FLORENCIA"]);
        City::create([ "id_departament"=>9, "name"=>"LA MONTAÑITA"]);
        City::create([ "id_departament"=>9, "name"=>"MORELIA"]);
        City::create([ "id_departament"=>9, "name"=>"PUERTO MILÁN"]);
        City::create([ "id_departament"=>9, "name"=>"PUERTO RICO"]);
        City::create([ "id_departament"=>9, "name"=>"SAN JOSÉ DEL FRAGUA"]);
        City::create([ "id_departament"=>9, "name"=>"SAN VICENTE DEL CAGUÁN"]);
        City::create([ "id_departament"=>9, "name"=>"SOLANO"]);
        City::create([ "id_departament"=>9, "name"=>"SOLITA"]);
        City::create([ "id_departament"=>9, "name"=>"VALPARAÍSO"]);
        City::create([ "id_departament"=>10, "name"=>"AGUAZUL"]);
        City::create([ "id_departament"=>10, "name"=>"CHÁMEZA"]);
        City::create([ "id_departament"=>10, "name"=>"HATO COROZAL"]);
        City::create([ "id_departament"=>10, "name"=>"LA SALINA"]);
        City::create([ "id_departament"=>10, "name"=>"MANÍ"]);
        City::create([ "id_departament"=>10, "name"=>"MONTERREY"]);
        City::create([ "id_departament"=>10, "name"=>"NUNCHÍA"]);
        City::create([ "id_departament"=>10, "name"=>"OROCUÉ"]);
        City::create([ "id_departament"=>10, "name"=>"PAZ DE ARIPORO"]);
        City::create([ "id_departament"=>10, "name"=>"PORE"]);
        City::create([ "id_departament"=>10, "name"=>"RECETOR"]);
        City::create([ "id_departament"=>10, "name"=>"SABANALARGA"]);
        City::create([ "id_departament"=>10, "name"=>"SÁCAMA"]);
        City::create([ "id_departament"=>10, "name"=>"SAN LUIS DE PALENQUE"]);
        City::create([ "id_departament"=>10, "name"=>"TÁMARA"]);
        City::create([ "id_departament"=>10, "name"=>"TAURAMENA"]);
        City::create([ "id_departament"=>10, "name"=>"TRINIDAD"]);
        City::create([ "id_departament"=>10, "name"=>"VILLANUEVA"]);
        City::create([ "id_departament"=>10, "name"=>"YOPAL"]);
        City::create([ "id_departament"=>11, "name"=>"ALMAGUER"]);
        City::create([ "id_departament"=>11, "name"=>"ARGELIA"]);
        City::create([ "id_departament"=>11, "name"=>"BALBOA"]);
        City::create([ "id_departament"=>11, "name"=>"BOLÍVAR"]);
        City::create([ "id_departament"=>11, "name"=>"BUENOS AIRES"]);
        City::create([ "id_departament"=>11, "name"=>"CAJIBÍO"]);
        City::create([ "id_departament"=>11, "name"=>"CALDONO"]);
        City::create([ "id_departament"=>11, "name"=>"CALOTO"]);
        City::create([ "id_departament"=>11, "name"=>"CORINTO"]);
        City::create([ "id_departament"=>11, "name"=>"EL TAMBO"]);
        City::create([ "id_departament"=>11, "name"=>"FLORENCIA"]);
        City::create([ "id_departament"=>11, "name"=>"GUACHENÉ"]);
        City::create([ "id_departament"=>11, "name"=>"GUAPI"]);
        City::create([ "id_departament"=>11, "name"=>"INZÁ"]);
        City::create([ "id_departament"=>11, "name"=>"JAMBALÓ"]);
        City::create([ "id_departament"=>11, "name"=>"LA SIERRA"]);
        City::create([ "id_departament"=>11, "name"=>"LA VEGA"]);
        City::create([ "id_departament"=>11, "name"=>"LÓPEZ DE MICAY"]);
        City::create([ "id_departament"=>11, "name"=>"MERCADERES"]);
        City::create([ "id_departament"=>11, "name"=>"MIRANDA"]);
        City::create([ "id_departament"=>11, "name"=>"MORALES"]);
        City::create([ "id_departament"=>11, "name"=>"PADILLA"]);
        City::create([ "id_departament"=>11, "name"=>"PÁEZ"]);
        City::create([ "id_departament"=>11, "name"=>"PATÍA"]);
        City::create([ "id_departament"=>11, "name"=>"PIAMONTE"]);
        City::create([ "id_departament"=>11, "name"=>"PIENDAMÓ"]);
        City::create([ "id_departament"=>11, "name"=>"POPAYÁN"]);
        City::create([ "id_departament"=>11, "name"=>"PUERTO TEJADA"]);
        City::create([ "id_departament"=>11, "name"=>"PURACÉ - COCONUCO"]);
        City::create([ "id_departament"=>11, "name"=>"ROSAS"]);
        City::create([ "id_departament"=>11, "name"=>"SAN SEBASTIÁN"]);
        City::create([ "id_departament"=>11, "name"=>"SANTA ROSA"]);
        City::create([ "id_departament"=>11, "name"=>"SANTANDER DE QUILICHAO"]);
        City::create([ "id_departament"=>11, "name"=>"SILVIA"]);
        City::create([ "id_departament"=>11, "name"=>"SOTARÁ"]);
        City::create([ "id_departament"=>11, "name"=>"SUÁREZ"]);
        City::create([ "id_departament"=>11, "name"=>"SUCRE"]);
        City::create([ "id_departament"=>11, "name"=>"TIMBÍO"]);
        City::create([ "id_departament"=>11, "name"=>"TIMBIQUÍ"]);
        City::create([ "id_departament"=>11, "name"=>"TORIBÍO"]);
        City::create([ "id_departament"=>11, "name"=>"TOTORÓ"]);
        City::create([ "id_departament"=>11, "name"=>"VILLA RICA"]);
        City::create([ "id_departament"=>12, "name"=>"AGUACHICA"]);
        City::create([ "id_departament"=>12, "name"=>"AGUSTÍN CODAZZI"]);
        City::create([ "id_departament"=>12, "name"=>"ASTREA"]);
        City::create([ "id_departament"=>12, "name"=>"BECERRIL"]);
        City::create([ "id_departament"=>12, "name"=>"BOSCONIA"]);
        City::create([ "id_departament"=>12, "name"=>"CHIMICHAGUA"]);
        City::create([ "id_departament"=>12, "name"=>"CHIRIGUANÁ"]);
        City::create([ "id_departament"=>12, "name"=>"CURUMANÍ"]);
        City::create([ "id_departament"=>12, "name"=>"EL COPEY"]);
        City::create([ "id_departament"=>12, "name"=>"EL PASO"]);
        City::create([ "id_departament"=>12, "name"=>"GAMARRA"]);
        City::create([ "id_departament"=>12, "name"=>"GONZÁLEZ"]);
        City::create([ "id_departament"=>12, "name"=>"LA GLORIA"]);
        City::create([ "id_departament"=>12, "name"=>"LA JAGUA DE IBIRICO"]);
        City::create([ "id_departament"=>12, "name"=>"LA PAZ"]);
        City::create([ "id_departament"=>12, "name"=>"MANAURE"]);
        City::create([ "id_departament"=>12, "name"=>"PAILITAS"]);
        City::create([ "id_departament"=>12, "name"=>"PELAYA"]);
        City::create([ "id_departament"=>12, "name"=>"PUEBLO BELLO"]);
        City::create([ "id_departament"=>12, "name"=>"RÍO DE ORO"]);
        City::create([ "id_departament"=>12, "name"=>"SAN ALBERTO"]);
        City::create([ "id_departament"=>12, "name"=>"SAN DIEGO"]);
        City::create([ "id_departament"=>12, "name"=>"SAN MARTÍN"]);
        City::create([ "id_departament"=>12, "name"=>"TAMALAMEQUE"]);
        City::create([ "id_departament"=>12, "name"=>"VALLEDUPAR"]);
        City::create([ "id_departament"=>13, "name"=>"ACANDÍ"]);
        City::create([ "id_departament"=>13, "name"=>"ALTO BAUDÓ"]);
        City::create([ "id_departament"=>13, "name"=>"ATRATO"]);
        City::create([ "id_departament"=>13, "name"=>"BAGADÓ"]);
        City::create([ "id_departament"=>13, "name"=>"BAHÍA SOLANO"]);
        City::create([ "id_departament"=>13, "name"=>"BAJO BAUDÓ"]);
        City::create([ "id_departament"=>13, "name"=>"BOJAYÁ"]);
        City::create([ "id_departament"=>13, "name"=>"CÉRTEGUI"]);
        City::create([ "id_departament"=>13, "name"=>"CONDOTO"]);
        City::create([ "id_departament"=>13, "name"=>"EL CANTÓN DE SAN PABLO"]);
        City::create([ "id_departament"=>13, "name"=>"EL CARMEN DE ATRATO"]);
        City::create([ "id_departament"=>13, "name"=>"EL CARMEN DEL DARIÉN"]);
        City::create([ "id_departament"=>13, "name"=>"EL LITORAL DE SAN JUAN"]);
        City::create([ "id_departament"=>13, "name"=>"ISTMINA"]);
        City::create([ "id_departament"=>13, "name"=>"JURADÓ"]);
        City::create([ "id_departament"=>13, "name"=>"LLORÓ"]);
        City::create([ "id_departament"=>13, "name"=>"MEDIO ATRATO"]);
        City::create([ "id_departament"=>13, "name"=>"MEDIO BAUDÓ"]);
        City::create([ "id_departament"=>13, "name"=>"MEDIO SAN JUAN"]);
        City::create([ "id_departament"=>13, "name"=>"NÓVITA"]);
        City::create([ "id_departament"=>13, "name"=>"NUEVO BELÉN DE BAJIRÁ"]);
        City::create([ "id_departament"=>13, "name"=>"NUQUÍ"]);
        City::create([ "id_departament"=>13, "name"=>"QUIBDÓ"]);
        City::create([ "id_departament"=>13, "name"=>"RÍO IRÓ"]);
        City::create([ "id_departament"=>13, "name"=>"RÍO QUITO"]);
        City::create([ "id_departament"=>13, "name"=>"RIOSUCIO"]);
        City::create([ "id_departament"=>13, "name"=>"SAN JOSÉ DEL PALMAR"]);
        City::create([ "id_departament"=>13, "name"=>"SIPÍ"]);
        City::create([ "id_departament"=>13, "name"=>"TADÓ"]);
        City::create([ "id_departament"=>13, "name"=>"UNGUÍA"]);
        City::create([ "id_departament"=>13, "name"=>"UNIÓN PANAMERICANA"]);
        City::create([ "id_departament"=>14, "name"=>"AYAPEL"]);
        City::create([ "id_departament"=>14, "name"=>"BUENAVISTA"]);
        City::create([ "id_departament"=>14, "name"=>"CANALETE"]);
        City::create([ "id_departament"=>14, "name"=>"CERETÉ"]);
        City::create([ "id_departament"=>14, "name"=>"CHIMÁ"]);
        City::create([ "id_departament"=>14, "name"=>"CHINÚ"]);
        City::create([ "id_departament"=>14, "name"=>"CIÉNAGA DE ORO"]);
        City::create([ "id_departament"=>14, "name"=>"COTORRA"]);
        City::create([ "id_departament"=>14, "name"=>"LA APARTADA"]);
        City::create([ "id_departament"=>14, "name"=>"LOS CÓRDOBAS"]);
        City::create([ "id_departament"=>14, "name"=>"MOMIL"]);
        City::create([ "id_departament"=>14, "name"=>"MONTELÍBANO"]);
        City::create([ "id_departament"=>14, "name"=>"MONTERÍA"]);
        City::create([ "id_departament"=>14, "name"=>"MOÑITOS"]);
        City::create([ "id_departament"=>14, "name"=>"PLANETA RICA"]);
        City::create([ "id_departament"=>14, "name"=>"PUEBLO NUEVO"]);
        City::create([ "id_departament"=>14, "name"=>"PUERTO ESCONDIDO"]);
        City::create([ "id_departament"=>14, "name"=>"PUERTO LIBERTADOR"]);
        City::create([ "id_departament"=>14, "name"=>"PURÍSIMA"]);
        City::create([ "id_departament"=>14, "name"=>"SAHAGÚN"]);
        City::create([ "id_departament"=>14, "name"=>"SAN ANDRÉS DE SOTAVENTO"]);
        City::create([ "id_departament"=>14, "name"=>"SAN ANTERO"]);
        City::create([ "id_departament"=>14, "name"=>"SAN BERNARDO DEL VIENTO"]);
        City::create([ "id_departament"=>14, "name"=>"SAN CARLOS"]);
        City::create([ "id_departament"=>14, "name"=>"SAN JOSÉ DE URÉ"]);
        City::create([ "id_departament"=>14, "name"=>"SAN PELAYO"]);
        City::create([ "id_departament"=>14, "name"=>"SANTA CRUZ DE LORICA"]);
        City::create([ "id_departament"=>14, "name"=>"TIERRALTA"]);
        City::create([ "id_departament"=>14, "name"=>"TUCHÍN"]);
        City::create([ "id_departament"=>14, "name"=>"VALENCIA"]);
        City::create([ "id_departament"=>15, "name"=>"AGUA DE DIOS"]);
        City::create([ "id_departament"=>15, "name"=>"ALBÁN"]);
        City::create([ "id_departament"=>15, "name"=>"ANAPOIMA"]);
        City::create([ "id_departament"=>15, "name"=>"ANOLAIMA"]);
        City::create([ "id_departament"=>15, "name"=>"APULO"]);
        City::create([ "id_departament"=>15, "name"=>"ARBELÁEZ"]);
        City::create([ "id_departament"=>15, "name"=>"BELTRÁN"]);
        City::create([ "id_departament"=>15, "name"=>"BITUIMA"]);
        City::create([ "id_departament"=>15, "name"=>"BOGOTA"]);
        City::create([ "id_departament"=>15, "name"=>"BOJACÁ"]);
        City::create([ "id_departament"=>15, "name"=>"CABRERA"]);
        City::create([ "id_departament"=>15, "name"=>"CACHIPAY"]);
        City::create([ "id_departament"=>15, "name"=>"CAJICÁ"]);
        City::create([ "id_departament"=>15, "name"=>"CAPARRAPÍ"]);
        City::create([ "id_departament"=>15, "name"=>"CÁQUEZA"]);
        City::create([ "id_departament"=>15, "name"=>"CARMEN DE CARUPA"]);
        City::create([ "id_departament"=>15, "name"=>"CHAGUANÍ"]);
        City::create([ "id_departament"=>15, "name"=>"CHÍA"]);
        City::create([ "id_departament"=>15, "name"=>"CHIPAQUE"]);
        City::create([ "id_departament"=>15, "name"=>"CHOACHÍ"]);
        City::create([ "id_departament"=>15, "name"=>"CHOCONTÁ"]);
        City::create([ "id_departament"=>15, "name"=>"COGUA"]);
        City::create([ "id_departament"=>15, "name"=>"COTA"]);
        City::create([ "id_departament"=>15, "name"=>"CUCUNUBÁ"]);
        City::create([ "id_departament"=>15, "name"=>"EL COLEGIO"]);
        City::create([ "id_departament"=>15, "name"=>"EL PEÑÓN"]);
        City::create([ "id_departament"=>15, "name"=>"EL ROSAL"]);
        City::create([ "id_departament"=>15, "name"=>"FACATATIVÁ"]);
        City::create([ "id_departament"=>15, "name"=>"FÓMEQUE"]);
        City::create([ "id_departament"=>15, "name"=>"FOSCA"]);
        City::create([ "id_departament"=>15, "name"=>"FUNZA"]);
        City::create([ "id_departament"=>15, "name"=>"FÚQUENE"]);
        City::create([ "id_departament"=>15, "name"=>"FUSAGASUGÁ"]);
        City::create([ "id_departament"=>15, "name"=>"GACHALÁ"]);
        City::create([ "id_departament"=>15, "name"=>"GACHANCIPÁ"]);
        City::create([ "id_departament"=>15, "name"=>"GACHETÁ"]);
        City::create([ "id_departament"=>15, "name"=>"GAMA"]);
        City::create([ "id_departament"=>15, "name"=>"GIRARDOT"]);
        City::create([ "id_departament"=>15, "name"=>"GRANADA"]);
        City::create([ "id_departament"=>15, "name"=>"GUACHETÁ"]);
        City::create([ "id_departament"=>15, "name"=>"GUADUAS"]);
        City::create([ "id_departament"=>15, "name"=>"GUASCA"]);
        City::create([ "id_departament"=>15, "name"=>"GUATAQUÍ"]);
        City::create([ "id_departament"=>15, "name"=>"GUATAVITA"]);
        City::create([ "id_departament"=>15, "name"=>"GUAYABAL DE SÍQUIMA"]);
        City::create([ "id_departament"=>15, "name"=>"GUAYABETAL"]);
        City::create([ "id_departament"=>15, "name"=>"GUTIÉRREZ"]);
        City::create([ "id_departament"=>15, "name"=>"JERUSALÉN"]);
        City::create([ "id_departament"=>15, "name"=>"JUNÍN"]);
        City::create([ "id_departament"=>15, "name"=>"LA CALERA"]);
        City::create([ "id_departament"=>15, "name"=>"LA MESA"]);
        City::create([ "id_departament"=>15, "name"=>"LA PALMA"]);
        City::create([ "id_departament"=>15, "name"=>"LA PEÑA"]);
        City::create([ "id_departament"=>15, "name"=>"LA VEGA"]);
        City::create([ "id_departament"=>15, "name"=>"LENGUAZAQUE"]);
        City::create([ "id_departament"=>15, "name"=>"MACHETÁ"]);
        City::create([ "id_departament"=>15, "name"=>"MADRID"]);
        City::create([ "id_departament"=>15, "name"=>"MANTA"]);
        City::create([ "id_departament"=>15, "name"=>"MEDINA"]);
        City::create([ "id_departament"=>15, "name"=>"MOSQUERA"]);
        City::create([ "id_departament"=>15, "name"=>"NARIÑO"]);
        City::create([ "id_departament"=>15, "name"=>"NEMOCÓN"]);
        City::create([ "id_departament"=>15, "name"=>"NILO"]);
        City::create([ "id_departament"=>15, "name"=>"NIMAIMA"]);
        City::create([ "id_departament"=>15, "name"=>"NOCAIMA"]);
        City::create([ "id_departament"=>15, "name"=>"PACHO"]);
        City::create([ "id_departament"=>15, "name"=>"PAIME"]);
        City::create([ "id_departament"=>15, "name"=>"PANDI"]);
        City::create([ "id_departament"=>15, "name"=>"PARATEBUENO"]);
        City::create([ "id_departament"=>15, "name"=>"PASCA"]);
        City::create([ "id_departament"=>15, "name"=>"PUERTO SALGAR"]);
        City::create([ "id_departament"=>15, "name"=>"PULÍ"]);
        City::create([ "id_departament"=>15, "name"=>"QUEBRADANEGRA"]);
        City::create([ "id_departament"=>15, "name"=>"QUETAME"]);
        City::create([ "id_departament"=>15, "name"=>"QUIPILE"]);
        City::create([ "id_departament"=>15, "name"=>"RICAURTE"]);
        City::create([ "id_departament"=>15, "name"=>"SAN ANTONIO DEL TEQUENDAMA"]);
        City::create([ "id_departament"=>15, "name"=>"SAN BERNARDO"]);
        City::create([ "id_departament"=>15, "name"=>"SAN CAYETANO"]);
        City::create([ "id_departament"=>15, "name"=>"SAN FRANCISCO"]);
        City::create([ "id_departament"=>15, "name"=>"SAN JUAN DE RIOSECO"]);
        City::create([ "id_departament"=>15, "name"=>"SASAIMA"]);
        City::create([ "id_departament"=>15, "name"=>"SESQUILÉ"]);
        City::create([ "id_departament"=>15, "name"=>"SIBATÉ"]);
        City::create([ "id_departament"=>15, "name"=>"SILVANIA"]);
        City::create([ "id_departament"=>15, "name"=>"SIMIJACA"]);
        City::create([ "id_departament"=>15, "name"=>"SOACHA"]);
        City::create([ "id_departament"=>15, "name"=>"SOPÓ"]);
        City::create([ "id_departament"=>15, "name"=>"SUBACHOQUE"]);
        City::create([ "id_departament"=>15, "name"=>"SUESCA"]);
        City::create([ "id_departament"=>15, "name"=>"SUPATÁ"]);
        City::create([ "id_departament"=>15, "name"=>"SUSA"]);
        City::create([ "id_departament"=>15, "name"=>"SUTATAUSA"]);
        City::create([ "id_departament"=>15, "name"=>"TABIO"]);
        City::create([ "id_departament"=>15, "name"=>"TAUSA"]);
        City::create([ "id_departament"=>15, "name"=>"TENA"]);
        City::create([ "id_departament"=>15, "name"=>"TENJO"]);
        City::create([ "id_departament"=>15, "name"=>"TIBACUY"]);
        City::create([ "id_departament"=>15, "name"=>"TIBIRITA"]);
        City::create([ "id_departament"=>15, "name"=>"TOCAIMA"]);
        City::create([ "id_departament"=>15, "name"=>"TOCANCIPÁ"]);
        City::create([ "id_departament"=>15, "name"=>"TOPAIPÍ"]);
        City::create([ "id_departament"=>15, "name"=>"UBALÁ"]);
        City::create([ "id_departament"=>15, "name"=>"UBAQUE"]);
        City::create([ "id_departament"=>15, "name"=>"UBATÉ"]);
        City::create([ "id_departament"=>15, "name"=>"UNE"]);
        City::create([ "id_departament"=>15, "name"=>"ÚTICA"]);
        City::create([ "id_departament"=>15, "name"=>"VENECIA"]);
        City::create([ "id_departament"=>15, "name"=>"VERGARA"]);
        City::create([ "id_departament"=>15, "name"=>"VIANÍ"]);
        City::create([ "id_departament"=>15, "name"=>"VILLAGÓMEZ"]);
        City::create([ "id_departament"=>15, "name"=>"VILLAPINZÓN"]);
        City::create([ "id_departament"=>15, "name"=>"VILLETA"]);
        City::create([ "id_departament"=>15, "name"=>"VIOTÁ"]);
        City::create([ "id_departament"=>15, "name"=>"YACOPÍ"]);
        City::create([ "id_departament"=>15, "name"=>"ZIPACÓN"]);
        City::create([ "id_departament"=>15, "name"=>"ZIPAQUIRÁ"]);
        City::create([ "id_departament"=>16, "name"=>"BARRANCOMINAS"]);
        City::create([ "id_departament"=>16, "name"=>"INIRIDA"]);
        City::create([ "id_departament"=>17, "name"=>"CALAMAR"]);
        City::create([ "id_departament"=>17, "name"=>"EL RETORNO"]);
        City::create([ "id_departament"=>17, "name"=>"MIRAFLORES"]);
        City::create([ "id_departament"=>17, "name"=>"SAN JOSÉ DEL GUAVIARE"]);
        City::create([ "id_departament"=>18, "name"=>"ACEVEDO"]);
        City::create([ "id_departament"=>18, "name"=>"AGRADO"]);
        City::create([ "id_departament"=>18, "name"=>"AIPE"]);
        City::create([ "id_departament"=>18, "name"=>"ALGECIRAS"]);
        City::create([ "id_departament"=>18, "name"=>"ALTAMIRA"]);
        City::create([ "id_departament"=>18, "name"=>"BARAYA"]);
        City::create([ "id_departament"=>18, "name"=>"CAMPOALEGRE"]);
        City::create([ "id_departament"=>18, "name"=>"COLOMBIA"]);
        City::create([ "id_departament"=>18, "name"=>"ELÍAS"]);
        City::create([ "id_departament"=>18, "name"=>"GARZÓN"]);
        City::create([ "id_departament"=>18, "name"=>"GIGANTE"]);
        City::create([ "id_departament"=>18, "name"=>"GUADALUPE"]);
        City::create([ "id_departament"=>18, "name"=>"HOBO"]);
        City::create([ "id_departament"=>18, "name"=>"ÍQUIRA"]);
        City::create([ "id_departament"=>18, "name"=>"ISNOS"]);
        City::create([ "id_departament"=>18, "name"=>"LA ARGENTINA"]);
        City::create([ "id_departament"=>18, "name"=>"LA PLATA"]);
        City::create([ "id_departament"=>18, "name"=>"NÁTAGA"]);
        City::create([ "id_departament"=>18, "name"=>"NEIVA"]);
        City::create([ "id_departament"=>18, "name"=>"OPORAPA"]);
        City::create([ "id_departament"=>18, "name"=>"PAICOL"]);
        City::create([ "id_departament"=>18, "name"=>"PALERMO"]);
        City::create([ "id_departament"=>18, "name"=>"PALESTINA"]);
        City::create([ "id_departament"=>18, "name"=>"PITAL"]);
        City::create([ "id_departament"=>18, "name"=>"PITALITO"]);
        City::create([ "id_departament"=>18, "name"=>"RIVERA"]);
        City::create([ "id_departament"=>18, "name"=>"SALADOBLANCO"]);
        City::create([ "id_departament"=>18, "name"=>"SAN AGUSTÍN"]);
        City::create([ "id_departament"=>18, "name"=>"SANTA MARÍA"]);
        City::create([ "id_departament"=>18, "name"=>"SUAZA"]);
        City::create([ "id_departament"=>18, "name"=>"TARQUI"]);
        City::create([ "id_departament"=>18, "name"=>"TELLO"]);
        City::create([ "id_departament"=>18, "name"=>"TERUEL"]);
        City::create([ "id_departament"=>18, "name"=>"TESALIA"]);
        City::create([ "id_departament"=>18, "name"=>"TIMANÁ"]);
        City::create([ "id_departament"=>18, "name"=>"VILLAVIEJA"]);
        City::create([ "id_departament"=>18, "name"=>"YAGUARÁ"]);
        City::create([ "id_departament"=>19, "name"=>"ALBANIA"]);
        City::create([ "id_departament"=>19, "name"=>"BARRANCAS"]);
        City::create([ "id_departament"=>19, "name"=>"DIBULLA"]);
        City::create([ "id_departament"=>19, "name"=>"DISTRACCIÓN"]);
        City::create([ "id_departament"=>19, "name"=>"EL MOLINO"]);
        City::create([ "id_departament"=>19, "name"=>"FONSECA"]);
        City::create([ "id_departament"=>19, "name"=>"HATONUEVO"]);
        City::create([ "id_departament"=>19, "name"=>"LA JAGUA DEL PILAR"]);
        City::create([ "id_departament"=>19, "name"=>"MAICAO"]);
        City::create([ "id_departament"=>19, "name"=>"MANAURE"]);
        City::create([ "id_departament"=>19, "name"=>"RIOHACHA"]);
        City::create([ "id_departament"=>19, "name"=>"SAN JUAN DEL CESAR"]);
        City::create([ "id_departament"=>19, "name"=>"URIBIA"]);
        City::create([ "id_departament"=>19, "name"=>"URUMITA"]);
        City::create([ "id_departament"=>19, "name"=>"VILLANUEVA"]);
        City::create([ "id_departament"=>20, "name"=>"ALGARROBO"]);
        City::create([ "id_departament"=>20, "name"=>"ARACATACA"]);
        City::create([ "id_departament"=>20, "name"=>"ARIGUANÍ"]);
        City::create([ "id_departament"=>20, "name"=>"CERRO DE SAN ANTONIO"]);
        City::create([ "id_departament"=>20, "name"=>"CHIBOLO"]);
        City::create([ "id_departament"=>20, "name"=>"CIÉNAGA"]);
        City::create([ "id_departament"=>20, "name"=>"CONCORDIA"]);
        City::create([ "id_departament"=>20, "name"=>"EL BANCO"]);
        City::create([ "id_departament"=>20, "name"=>"EL PIÑÓN"]);
        City::create([ "id_departament"=>20, "name"=>"EL RETÉN"]);
        City::create([ "id_departament"=>20, "name"=>"FUNDACIÓN"]);
        City::create([ "id_departament"=>20, "name"=>"GUAMAL"]);
        City::create([ "id_departament"=>20, "name"=>"NUEVA GRANADA"]);
        City::create([ "id_departament"=>20, "name"=>"PEDRAZA"]);
        City::create([ "id_departament"=>20, "name"=>"PIJIÑO DEL CARMEN"]);
        City::create([ "id_departament"=>20, "name"=>"PIVIJAY"]);
        City::create([ "id_departament"=>20, "name"=>"PLATO"]);
        City::create([ "id_departament"=>20, "name"=>"PUEBLO VIEJO"]);
        City::create([ "id_departament"=>20, "name"=>"REMOLINO"]);
        City::create([ "id_departament"=>20, "name"=>"SABANAS DE SAN ÁNGEL"]);
        City::create([ "id_departament"=>20, "name"=>"SALAMINA"]);
        City::create([ "id_departament"=>20, "name"=>"SAN SEBASTIÁN DE BUENAVISTA"]);
        City::create([ "id_departament"=>20, "name"=>"SAN ZENÓN"]);
        City::create([ "id_departament"=>20, "name"=>"SANTA ANA"]);
        City::create([ "id_departament"=>20, "name"=>"SANTA BÁRBARA DE PINTO"]);
        City::create([ "id_departament"=>20, "name"=>"SANTA MARTA"]);
        City::create([ "id_departament"=>20, "name"=>"SITIONUEVO"]);
        City::create([ "id_departament"=>20, "name"=>"TENERIFE"]);
        City::create([ "id_departament"=>20, "name"=>"ZAPAYÁN"]);
        City::create([ "id_departament"=>20, "name"=>"ZONA BANANERA"]);
        City::create([ "id_departament"=>21, "name"=>"ACACÍAS"]);
        City::create([ "id_departament"=>21, "name"=>"BARRANCA DE UPÍA"]);
        City::create([ "id_departament"=>21, "name"=>"CABUYARO"]);
        City::create([ "id_departament"=>21, "name"=>"CASTILLA LA NUEVA"]);
        City::create([ "id_departament"=>21, "name"=>"CUBARRAL"]);
        City::create([ "id_departament"=>21, "name"=>"CUMARAL"]);
        City::create([ "id_departament"=>21, "name"=>"EL CALVARIO"]);
        City::create([ "id_departament"=>21, "name"=>"EL CASTILLO"]);
        City::create([ "id_departament"=>21, "name"=>"EL DORADO"]);
        City::create([ "id_departament"=>21, "name"=>"FUENTE DE ORO"]);
        City::create([ "id_departament"=>21, "name"=>"GRANADA"]);
        City::create([ "id_departament"=>21, "name"=>"GUAMAL"]);
        City::create([ "id_departament"=>21, "name"=>"LA MACARENA"]);
        City::create([ "id_departament"=>21, "name"=>"LA URIBE"]);
        City::create([ "id_departament"=>21, "name"=>"LEJANÍAS"]);
        City::create([ "id_departament"=>21, "name"=>"MAPIRIPÁN"]);
        City::create([ "id_departament"=>21, "name"=>"MESETAS"]);
        City::create([ "id_departament"=>21, "name"=>"PUERTO CONCORDIA"]);
        City::create([ "id_departament"=>21, "name"=>"PUERTO GAITÁN"]);
        City::create([ "id_departament"=>21, "name"=>"PUERTO LLERAS"]);
        City::create([ "id_departament"=>21, "name"=>"PUERTO LÓPEZ"]);
        City::create([ "id_departament"=>21, "name"=>"PUERTO RICO"]);
        City::create([ "id_departament"=>21, "name"=>"RESTREPO"]);
        City::create([ "id_departament"=>21, "name"=>"SAN CARLOS DE GUAROA"]);
        City::create([ "id_departament"=>21, "name"=>"SAN JUAN DE ARAMA"]);
        City::create([ "id_departament"=>21, "name"=>"SAN JUANITO"]);
        City::create([ "id_departament"=>21, "name"=>"SAN MARTÍN"]);
        City::create([ "id_departament"=>21, "name"=>"VILLAVICENCIO"]);
        City::create([ "id_departament"=>21, "name"=>"VISTA HERMOSA"]);
        City::create([ "id_departament"=>22, "name"=>"ALBÁN"]);
        City::create([ "id_departament"=>22, "name"=>"ALDANA"]);
        City::create([ "id_departament"=>22, "name"=>"ANCUYA"]);
        City::create([ "id_departament"=>22, "name"=>"ARBOLEDA"]);
        City::create([ "id_departament"=>22, "name"=>"BARBACOAS"]);
        City::create([ "id_departament"=>22, "name"=>"BELÉN"]);
        City::create([ "id_departament"=>22, "name"=>"BUESACO"]);
        City::create([ "id_departament"=>22, "name"=>"CHACHAGÜÍ"]);
        City::create([ "id_departament"=>22, "name"=>"COLÓN"]);
        City::create([ "id_departament"=>22, "name"=>"CONSACÁ"]);
        City::create([ "id_departament"=>22, "name"=>"CONTADERO"]);
        City::create([ "id_departament"=>22, "name"=>"CÓRDOBA"]);
        City::create([ "id_departament"=>22, "name"=>"CUASPUD"]);
        City::create([ "id_departament"=>22, "name"=>"CUMBAL"]);
        City::create([ "id_departament"=>22, "name"=>"CUMBITARA"]);
        City::create([ "id_departament"=>22, "name"=>"EL CHARCO"]);
        City::create([ "id_departament"=>22, "name"=>"EL PEÑOL"]);
        City::create([ "id_departament"=>22, "name"=>"EL ROSARIO"]);
        City::create([ "id_departament"=>22, "name"=>"EL TABLÓN DE GÓMEZ"]);
        City::create([ "id_departament"=>22, "name"=>"EL TAMBO"]);
        City::create([ "id_departament"=>22, "name"=>"FRANCISCO PIZARRO"]);
        City::create([ "id_departament"=>22, "name"=>"FUNES"]);
        City::create([ "id_departament"=>22, "name"=>"GUACHUCAL"]);
        City::create([ "id_departament"=>22, "name"=>"GUAITARILLA"]);
        City::create([ "id_departament"=>22, "name"=>"GUALMATÁN"]);
        City::create([ "id_departament"=>22, "name"=>"ILES"]);
        City::create([ "id_departament"=>22, "name"=>"IMUÉS"]);
        City::create([ "id_departament"=>22, "name"=>"IPIALES"]);
        City::create([ "id_departament"=>22, "name"=>"LA CRUZ"]);
        City::create([ "id_departament"=>22, "name"=>"LA FLORIDA"]);
        City::create([ "id_departament"=>22, "name"=>"LA LLANADA"]);
        City::create([ "id_departament"=>22, "name"=>"LA TOLA"]);
        City::create([ "id_departament"=>22, "name"=>"LA UNIÓN"]);
        City::create([ "id_departament"=>22, "name"=>"LEIVA"]);
        City::create([ "id_departament"=>22, "name"=>"LINARES"]);
        City::create([ "id_departament"=>22, "name"=>"LOS ANDES"]);
        City::create([ "id_departament"=>22, "name"=>"MAGÜÍ PAYÁN"]);
        City::create([ "id_departament"=>22, "name"=>"MALLAMA"]);
        City::create([ "id_departament"=>22, "name"=>"MOSQUERA"]);
        City::create([ "id_departament"=>22, "name"=>"NARIÑO"]);
        City::create([ "id_departament"=>22, "name"=>"OLAYA HERRERA"]);
        City::create([ "id_departament"=>22, "name"=>"OSPINA"]);
        City::create([ "id_departament"=>22, "name"=>"PASTO"]);
        City::create([ "id_departament"=>22, "name"=>"POLICARPA"]);
        City::create([ "id_departament"=>22, "name"=>"POTOSÍ"]);
        City::create([ "id_departament"=>22, "name"=>"PROVIDENCIA"]);
        City::create([ "id_departament"=>22, "name"=>"PUERRES"]);
        City::create([ "id_departament"=>22, "name"=>"PUPIALES"]);
        City::create([ "id_departament"=>22, "name"=>"RICAURTE"]);
        City::create([ "id_departament"=>22, "name"=>"ROBERTO PAYÁN"]);
        City::create([ "id_departament"=>22, "name"=>"SAMANIEGO"]);
        City::create([ "id_departament"=>22, "name"=>"SAN BERNARDO"]);
        City::create([ "id_departament"=>22, "name"=>"SAN LORENZO"]);
        City::create([ "id_departament"=>22, "name"=>"SAN PABLO"]);
        City::create([ "id_departament"=>22, "name"=>"SAN PEDRO DE CARTAGO"]);
        City::create([ "id_departament"=>22, "name"=>"SANDONÁ"]);
        City::create([ "id_departament"=>22, "name"=>"SANTA BÁRBARA"]);
        City::create([ "id_departament"=>22, "name"=>"SANTACRUZ"]);
        City::create([ "id_departament"=>22, "name"=>"SAPUYES"]);
        City::create([ "id_departament"=>22, "name"=>"TAMINANGO"]);
        City::create([ "id_departament"=>22, "name"=>"TANGUA"]);
        City::create([ "id_departament"=>22, "name"=>"TUMACO"]);
        City::create([ "id_departament"=>22, "name"=>"TÚQUERRES"]);
        City::create([ "id_departament"=>22, "name"=>"YACUANQUER"]);
        City::create([ "id_departament"=>23, "name"=>"ÁBREGO"]);
        City::create([ "id_departament"=>23, "name"=>"ARBOLEDAS"]);
        City::create([ "id_departament"=>23, "name"=>"BOCHALEMA"]);
        City::create([ "id_departament"=>23, "name"=>"BUCARASICA"]);
        City::create([ "id_departament"=>23, "name"=>"CÁCHIRA"]);
        City::create([ "id_departament"=>23, "name"=>"CÁCOTA"]);
        City::create([ "id_departament"=>23, "name"=>"CHINÁCOTA"]);
        City::create([ "id_departament"=>23, "name"=>"CHITAGÁ"]);
        City::create([ "id_departament"=>23, "name"=>"CONVENCIÓN"]);
        City::create([ "id_departament"=>23, "name"=>"CUCUTA"]);
        City::create([ "id_departament"=>23, "name"=>"CUCUTILLA"]);
        City::create([ "id_departament"=>23, "name"=>"DURANIA"]);
        City::create([ "id_departament"=>23, "name"=>"EL CARMEN"]);
        City::create([ "id_departament"=>23, "name"=>"EL TARRA"]);
        City::create([ "id_departament"=>23, "name"=>"EL ZULIA"]);
        City::create([ "id_departament"=>23, "name"=>"GRAMALOTE"]);
        City::create([ "id_departament"=>23, "name"=>"HACARÍ"]);
        City::create([ "id_departament"=>23, "name"=>"HERRÁN"]);
        City::create([ "id_departament"=>23, "name"=>"LA ESPERANZA"]);
        City::create([ "id_departament"=>23, "name"=>"LA PLAYA DE BELÉN"]);
        City::create([ "id_departament"=>23, "name"=>"LABATECA"]);
        City::create([ "id_departament"=>23, "name"=>"LOS PATIOS"]);
        City::create([ "id_departament"=>23, "name"=>"LOURDES"]);
        City::create([ "id_departament"=>23, "name"=>"MUTISCUA"]);
        City::create([ "id_departament"=>23, "name"=>"OCAÑA"]);
        City::create([ "id_departament"=>23, "name"=>"PAMPLONA"]);
        City::create([ "id_departament"=>23, "name"=>"PAMPLONITA"]);
        City::create([ "id_departament"=>23, "name"=>"PUERTO SANTANDER"]);
        City::create([ "id_departament"=>23, "name"=>"RAGONVALIA"]);
        City::create([ "id_departament"=>23, "name"=>"SALAZAR DE LAS PALMAS"]);
        City::create([ "id_departament"=>23, "name"=>"SAN CALIXTO"]);
        City::create([ "id_departament"=>23, "name"=>"SAN CAYETANO"]);
        City::create([ "id_departament"=>23, "name"=>"SANTIAGO"]);
        City::create([ "id_departament"=>23, "name"=>"SANTO DOMINGO DE SILOS"]);
        City::create([ "id_departament"=>23, "name"=>"SARDINATA"]);
        City::create([ "id_departament"=>23, "name"=>"TEORAMA"]);
        City::create([ "id_departament"=>23, "name"=>"TIBÚ"]);
        City::create([ "id_departament"=>23, "name"=>"TOLEDO"]);
        City::create([ "id_departament"=>23, "name"=>"VILLA CARO"]);
        City::create([ "id_departament"=>23, "name"=>"VILLA DEL ROSARIO"]);
        City::create([ "id_departament"=>24, "name"=>"COLÓN"]);
        City::create([ "id_departament"=>24, "name"=>"MOCOA"]);
        City::create([ "id_departament"=>24, "name"=>"ORITO"]);
        City::create([ "id_departament"=>24, "name"=>"PUERTO ASÍS"]);
        City::create([ "id_departament"=>24, "name"=>"PUERTO CAICEDO"]);
        City::create([ "id_departament"=>24, "name"=>"PUERTO GUZMÁN"]);
        City::create([ "id_departament"=>24, "name"=>"PUERTO LEGUÍZAMO"]);
        City::create([ "id_departament"=>24, "name"=>"SAN FRANCISCO"]);
        City::create([ "id_departament"=>24, "name"=>"SAN MIGUEL"]);
        City::create([ "id_departament"=>24, "name"=>"SANTIAGO"]);
        City::create([ "id_departament"=>24, "name"=>"SIBUNDOY"]);
        City::create([ "id_departament"=>24, "name"=>"VALLE DEL GUAMUEZ"]);
        City::create([ "id_departament"=>24, "name"=>"VILLAGARZÓN"]);
        City::create([ "id_departament"=>25, "name"=>"ARMENIA"]);
        City::create([ "id_departament"=>25, "name"=>"BUENAVISTA"]);
        City::create([ "id_departament"=>25, "name"=>"CALARCÁ"]);
        City::create([ "id_departament"=>25, "name"=>"CIRCASIA"]);
        City::create([ "id_departament"=>25, "name"=>"CÓRDOBA"]);
        City::create([ "id_departament"=>25, "name"=>"FILANDIA"]);
        City::create([ "id_departament"=>25, "name"=>"GÉNOVA"]);
        City::create([ "id_departament"=>25, "name"=>"LA TEBAIDA"]);
        City::create([ "id_departament"=>25, "name"=>"MONTENEGRO"]);
        City::create([ "id_departament"=>25, "name"=>"PIJAO"]);
        City::create([ "id_departament"=>25, "name"=>"QUIMBAYA"]);
        City::create([ "id_departament"=>25, "name"=>"SALENTO"]);
        City::create([ "id_departament"=>26, "name"=>"APÍA"]);
        City::create([ "id_departament"=>26, "name"=>"BALBOA"]);
        City::create([ "id_departament"=>26, "name"=>"BELÉN DE UMBRÍA"]);
        City::create([ "id_departament"=>26, "name"=>"DOSQUEBRADAS"]);
        City::create([ "id_departament"=>26, "name"=>"GUÁTICA"]);
        City::create([ "id_departament"=>26, "name"=>"LA CELIA"]);
        City::create([ "id_departament"=>26, "name"=>"LA VIRGINIA"]);
        City::create([ "id_departament"=>26, "name"=>"MARSELLA"]);
        City::create([ "id_departament"=>26, "name"=>"MISTRATÓ"]);
        City::create([ "id_departament"=>26, "name"=>"PEREIRA"]);
        City::create([ "id_departament"=>26, "name"=>"PUEBLO RICO"]);
        City::create([ "id_departament"=>26, "name"=>"QUINCHÍA"]);
        City::create([ "id_departament"=>26, "name"=>"SANTA ROSA DE CABAL"]);
        City::create([ "id_departament"=>26, "name"=>"SANTUARIO"]);
        City::create([ "id_departament"=>27, "name"=>"PROVIDENCIA"]);
        City::create([ "id_departament"=>28, "name"=>"AGUADA"]);
        City::create([ "id_departament"=>28, "name"=>"ALBANIA"]);
        City::create([ "id_departament"=>28, "name"=>"ARATOCA"]);
        City::create([ "id_departament"=>28, "name"=>"BARBOSA"]);
        City::create([ "id_departament"=>28, "name"=>"BARICHARA"]);
        City::create([ "id_departament"=>28, "name"=>"BARRANCABERMEJA"]);
        City::create([ "id_departament"=>28, "name"=>"BETULIA"]);
        City::create([ "id_departament"=>28, "name"=>"BOLÍVAR"]);
        City::create([ "id_departament"=>28, "name"=>"BUCARAMANGA"]);
        City::create([ "id_departament"=>28, "name"=>"CABRERA"]);
        City::create([ "id_departament"=>28, "name"=>"CALIFORNIA"]);
        City::create([ "id_departament"=>28, "name"=>"CAPITANEJO"]);
        City::create([ "id_departament"=>28, "name"=>"CARCASÍ"]);
        City::create([ "id_departament"=>28, "name"=>"CEPITÁ"]);
        City::create([ "id_departament"=>28, "name"=>"CERRITO"]);
        City::create([ "id_departament"=>28, "name"=>"CHARALÁ"]);
        City::create([ "id_departament"=>28, "name"=>"CHARTA"]);
        City::create([ "id_departament"=>28, "name"=>"CHIMA"]);
        City::create([ "id_departament"=>28, "name"=>"CHIPATÁ"]);
        City::create([ "id_departament"=>28, "name"=>"CIMITARRA"]);
        City::create([ "id_departament"=>28, "name"=>"CONCEPCIÓN"]);
        City::create([ "id_departament"=>28, "name"=>"CONFINES"]);
        City::create([ "id_departament"=>28, "name"=>"CONTRATACIÓN"]);
        City::create([ "id_departament"=>28, "name"=>"COROMORO"]);
        City::create([ "id_departament"=>28, "name"=>"CURITÍ"]);
        City::create([ "id_departament"=>28, "name"=>"EL CARMEN DE CHUCURÍ"]);
        City::create([ "id_departament"=>28, "name"=>"EL GUACAMAYO"]);
        City::create([ "id_departament"=>28, "name"=>"EL PEÑÓN"]);
        City::create([ "id_departament"=>28, "name"=>"EL PLAYÓN"]);
        City::create([ "id_departament"=>28, "name"=>"ENCINO"]);
        City::create([ "id_departament"=>28, "name"=>"ENCISO"]);
        City::create([ "id_departament"=>28, "name"=>"FLORIÁN"]);
        City::create([ "id_departament"=>28, "name"=>"FLORIDABLANCA"]);
        City::create([ "id_departament"=>28, "name"=>"GALÁN"]);
        City::create([ "id_departament"=>28, "name"=>"GÁMBITA"]);
        City::create([ "id_departament"=>28, "name"=>"GIRÓN"]);
        City::create([ "id_departament"=>28, "name"=>"GUACA"]);
        City::create([ "id_departament"=>28, "name"=>"GUADALUPE"]);
        City::create([ "id_departament"=>28, "name"=>"GUAPOTÁ"]);
        City::create([ "id_departament"=>28, "name"=>"GUAVATÁ"]);
        City::create([ "id_departament"=>28, "name"=>"GÜEPSA"]);
        City::create([ "id_departament"=>28, "name"=>"HATO"]);
        City::create([ "id_departament"=>28, "name"=>"JESÚS MARÍA"]);
        City::create([ "id_departament"=>28, "name"=>"JORDÁN"]);
        City::create([ "id_departament"=>28, "name"=>"LA BELLEZA"]);
        City::create([ "id_departament"=>28, "name"=>"LA PAZ"]);
        City::create([ "id_departament"=>28, "name"=>"LANDÁZURI"]);
        City::create([ "id_departament"=>28, "name"=>"LEBRIJA"]);
        City::create([ "id_departament"=>28, "name"=>"LOS SANTOS"]);
        City::create([ "id_departament"=>28, "name"=>"MACARAVITA"]);
        City::create([ "id_departament"=>28, "name"=>"MÁLAGA"]);
        City::create([ "id_departament"=>28, "name"=>"MATANZA"]);
        City::create([ "id_departament"=>28, "name"=>"MOGOTES"]);
        City::create([ "id_departament"=>28, "name"=>"MOLAGAVITA"]);
        City::create([ "id_departament"=>28, "name"=>"OCAMONTE"]);
        City::create([ "id_departament"=>28, "name"=>"OIBA"]);
        City::create([ "id_departament"=>28, "name"=>"ONZAGA"]);
        City::create([ "id_departament"=>28, "name"=>"PALMAR"]);
        City::create([ "id_departament"=>28, "name"=>"PALMAS DEL SOCORRO"]);
        City::create([ "id_departament"=>28, "name"=>"PÁRAMO"]);
        City::create([ "id_departament"=>28, "name"=>"PIEDECUESTA"]);
        City::create([ "id_departament"=>28, "name"=>"PINCHOTE"]);
        City::create([ "id_departament"=>28, "name"=>"PUENTE NACIONAL"]);
        City::create([ "id_departament"=>28, "name"=>"PUERTO PARRA"]);
        City::create([ "id_departament"=>28, "name"=>"PUERTO WILCHES"]);
        City::create([ "id_departament"=>28, "name"=>"RIONEGRO"]);
        City::create([ "id_departament"=>28, "name"=>"SABANA DE TORRES"]);
        City::create([ "id_departament"=>28, "name"=>"SAN ANDRÉS"]);
        City::create([ "id_departament"=>28, "name"=>"SAN BENITO"]);
        City::create([ "id_departament"=>28, "name"=>"SAN GIL"]);
        City::create([ "id_departament"=>28, "name"=>"SAN JOAQUÍN"]);
        City::create([ "id_departament"=>28, "name"=>"SAN JOSÉ DE MIRANDA"]);
        City::create([ "id_departament"=>28, "name"=>"SAN MIGUEL"]);
        City::create([ "id_departament"=>28, "name"=>"SAN VICENTE DE CHUCURÍ"]);
        City::create([ "id_departament"=>28, "name"=>"SANTA BÁRBARA"]);
        City::create([ "id_departament"=>28, "name"=>"SANTA HELENA DEL OPÓN"]);
        City::create([ "id_departament"=>28, "name"=>"SIMACOTA"]);
        City::create([ "id_departament"=>28, "name"=>"SOCORRO"]);
        City::create([ "id_departament"=>28, "name"=>"SUAITA"]);
        City::create([ "id_departament"=>28, "name"=>"SUCRE"]);
        City::create([ "id_departament"=>28, "name"=>"SURATÁ"]);
        City::create([ "id_departament"=>28, "name"=>"TONA"]);
        City::create([ "id_departament"=>28, "name"=>"VALLE DE SAN JOSÉ"]);
        City::create([ "id_departament"=>28, "name"=>"VÉLEZ"]);
        City::create([ "id_departament"=>28, "name"=>"VETAS"]);
        City::create([ "id_departament"=>28, "name"=>"VILLANUEVA"]);
        City::create([ "id_departament"=>28, "name"=>"ZAPATOCA"]);
        City::create([ "id_departament"=>29, "name"=>"BUENAVISTA"]);
        City::create([ "id_departament"=>29, "name"=>"CAIMITO"]);
        City::create([ "id_departament"=>29, "name"=>"CHALÁN"]);
        City::create([ "id_departament"=>29, "name"=>"COLOSÓ"]);
        City::create([ "id_departament"=>29, "name"=>"COROZAL"]);
        City::create([ "id_departament"=>29, "name"=>"COVEÑAS"]);
        City::create([ "id_departament"=>29, "name"=>"EL ROBLE"]);
        City::create([ "id_departament"=>29, "name"=>"GALERAS"]);
        City::create([ "id_departament"=>29, "name"=>"GUARANDA"]);
        City::create([ "id_departament"=>29, "name"=>"LA UNIÓN"]);
        City::create([ "id_departament"=>29, "name"=>"LOS PALMITOS"]);
        City::create([ "id_departament"=>29, "name"=>"MAJAGUAL"]);
        City::create([ "id_departament"=>29, "name"=>"MORROA"]);
        City::create([ "id_departament"=>29, "name"=>"OVEJAS"]);
        City::create([ "id_departament"=>29, "name"=>"PALMITO"]);
        City::create([ "id_departament"=>29, "name"=>"SAMPUÉS"]);
        City::create([ "id_departament"=>29, "name"=>"SAN BENITO ABAD"]);
        City::create([ "id_departament"=>29, "name"=>"SAN JUAN DE BETULIA"]);
        City::create([ "id_departament"=>29, "name"=>"SAN MARCOS"]);
        City::create([ "id_departament"=>29, "name"=>"SAN ONOFRE"]);
        City::create([ "id_departament"=>29, "name"=>"SAN PEDRO"]);
        City::create([ "id_departament"=>29, "name"=>"SANTIAGO DE TOLÚ"]);
        City::create([ "id_departament"=>29, "name"=>"SINCÉ"]);
        City::create([ "id_departament"=>29, "name"=>"SINCELEJO"]);
        City::create([ "id_departament"=>29, "name"=>"SUCRE"]);
        City::create([ "id_departament"=>29, "name"=>"TOLUVIEJO"]);
        City::create([ "id_departament"=>30, "name"=>"ALPUJARRA"]);
        City::create([ "id_departament"=>30, "name"=>"ALVARADO"]);
        City::create([ "id_departament"=>30, "name"=>"AMBALEMA"]);
        City::create([ "id_departament"=>30, "name"=>"ANZOÁTEGUI"]);
        City::create([ "id_departament"=>30, "name"=>"ARMERO"]);
        City::create([ "id_departament"=>30, "name"=>"ATACO"]);
        City::create([ "id_departament"=>30, "name"=>"CAJAMARCA"]);
        City::create([ "id_departament"=>30, "name"=>"CARMEN DE APICALÁ"]);
        City::create([ "id_departament"=>30, "name"=>"CASABIANCA"]);
        City::create([ "id_departament"=>30, "name"=>"CHAPARRAL"]);
        City::create([ "id_departament"=>30, "name"=>"COELLO"]);
        City::create([ "id_departament"=>30, "name"=>"COYAIMA"]);
        City::create([ "id_departament"=>30, "name"=>"CUNDAY"]);
        City::create([ "id_departament"=>30, "name"=>"DOLORES"]);
        City::create([ "id_departament"=>30, "name"=>"ESPINAL"]);
        City::create([ "id_departament"=>30, "name"=>"FALAN"]);
        City::create([ "id_departament"=>30, "name"=>"FLANDES"]);
        City::create([ "id_departament"=>30, "name"=>"FRESNO"]);
        City::create([ "id_departament"=>30, "name"=>"GUAMO"]);
        City::create([ "id_departament"=>30, "name"=>"HERVEO"]);
        City::create([ "id_departament"=>30, "name"=>"HONDA"]);
        City::create([ "id_departament"=>30, "name"=>"IBAGUÉ"]);
        City::create([ "id_departament"=>30, "name"=>"ICONONZO"]);
        City::create([ "id_departament"=>30, "name"=>"LÉRIDA"]);
        City::create([ "id_departament"=>30, "name"=>"LÍBANO"]);
        City::create([ "id_departament"=>30, "name"=>"MARIQUITA"]);
        City::create([ "id_departament"=>30, "name"=>"MELGAR"]);
        City::create([ "id_departament"=>30, "name"=>"MURILLO"]);
        City::create([ "id_departament"=>30, "name"=>"NATAGAIMA"]);
        City::create([ "id_departament"=>30, "name"=>"ORTEGA"]);
        City::create([ "id_departament"=>30, "name"=>"PALOCABILDO"]);
        City::create([ "id_departament"=>30, "name"=>"PIEDRAS"]);
        City::create([ "id_departament"=>30, "name"=>"PLANADAS"]);
        City::create([ "id_departament"=>30, "name"=>"PRADO"]);
        City::create([ "id_departament"=>30, "name"=>"PURIFICACIÓN"]);
        City::create([ "id_departament"=>30, "name"=>"RIOBLANCO"]);
        City::create([ "id_departament"=>30, "name"=>"RONCESVALLES"]);
        City::create([ "id_departament"=>30, "name"=>"ROVIRA"]);
        City::create([ "id_departament"=>30, "name"=>"SALDAÑA"]);
        City::create([ "id_departament"=>30, "name"=>"SAN ANTONIO"]);
        City::create([ "id_departament"=>30, "name"=>"SAN LUIS"]);
        City::create([ "id_departament"=>30, "name"=>"SANTA ISABEL"]);
        City::create([ "id_departament"=>30, "name"=>"SUÁREZ"]);
        City::create([ "id_departament"=>30, "name"=>"VALLE DE SAN JUAN"]);
        City::create([ "id_departament"=>30, "name"=>"VENADILLO"]);
        City::create([ "id_departament"=>30, "name"=>"VILLAHERMOSA"]);
        City::create([ "id_departament"=>30, "name"=>"VILLARRICA"]);
        City::create([ "id_departament"=>31, "name"=>"ALCALÁ"]);
        City::create([ "id_departament"=>31, "name"=>"ANDALUCÍA"]);
        City::create([ "id_departament"=>31, "name"=>"ANSERMANUEVO"]);
        City::create([ "id_departament"=>31, "name"=>"ARGELIA"]);
        City::create([ "id_departament"=>31, "name"=>"BOLÍVAR"]);
        City::create([ "id_departament"=>31, "name"=>"BUENAVENTURA"]);
        City::create([ "id_departament"=>31, "name"=>"BUGA"]);
        City::create([ "id_departament"=>31, "name"=>"BUGALAGRANDE"]);
        City::create([ "id_departament"=>31, "name"=>"CAICEDONIA"]);
        City::create([ "id_departament"=>31, "name"=>"CALI"]);
        City::create([ "id_departament"=>31, "name"=>"CALIMA - EL DARIÉN"]);
        City::create([ "id_departament"=>31, "name"=>"CANDELARIA"]);
        City::create([ "id_departament"=>31, "name"=>"CARTAGO"]);
        City::create([ "id_departament"=>31, "name"=>"DAGUA"]);
        City::create([ "id_departament"=>31, "name"=>"EL ÁGUILA"]);
        City::create([ "id_departament"=>31, "name"=>"EL CAIRO"]);
        City::create([ "id_departament"=>31, "name"=>"EL CERRITO"]);
        City::create([ "id_departament"=>31, "name"=>"EL DOVIO"]);
        City::create([ "id_departament"=>31, "name"=>"FLORIDA"]);
        City::create([ "id_departament"=>31, "name"=>"GINEBRA"]);
        City::create([ "id_departament"=>31, "name"=>"GUACARÍ"]);
        City::create([ "id_departament"=>31, "name"=>"JAMUNDÍ"]);
        City::create([ "id_departament"=>31, "name"=>"LA CUMBRE"]);
        City::create([ "id_departament"=>31, "name"=>"LA UNIÓN"]);
        City::create([ "id_departament"=>31, "name"=>"LA VICTORIA"]);
        City::create([ "id_departament"=>31, "name"=>"OBANDO"]);
        City::create([ "id_departament"=>31, "name"=>"PALMIRA"]);
        City::create([ "id_departament"=>31, "name"=>"PRADERA"]);
        City::create([ "id_departament"=>31, "name"=>"RESTREPO"]);
        City::create([ "id_departament"=>31, "name"=>"RIOFRÍO"]);
        City::create([ "id_departament"=>31, "name"=>"ROLDANILLO"]);
        City::create([ "id_departament"=>31, "name"=>"SAN PEDRO"]);
        City::create([ "id_departament"=>31, "name"=>"SEVILLA"]);
        City::create([ "id_departament"=>31, "name"=>"TORO"]);
        City::create([ "id_departament"=>31, "name"=>"TRUJILLO"]);
        City::create([ "id_departament"=>31, "name"=>"TULUÁ"]);
        City::create([ "id_departament"=>31, "name"=>"ULLOA"]);
        City::create([ "id_departament"=>31, "name"=>"VERSALLES"]);
        City::create([ "id_departament"=>31, "name"=>"VIJES"]);
        City::create([ "id_departament"=>31, "name"=>"YOTOCO"]);
        City::create([ "id_departament"=>31, "name"=>"YUMBO"]);
        City::create([ "id_departament"=>31, "name"=>"ZARZAL"]);
        City::create([ "id_departament"=>32, "name"=>"CARURU"]);
        City::create([ "id_departament"=>32, "name"=>"MITU"]);
        City::create([ "id_departament"=>32, "name"=>"TARAIRA"]);
        City::create([ "id_departament"=>33, "name"=>"CUMARIBO"]);
        City::create([ "id_departament"=>33, "name"=>"LA PRIMAVERA"]);
        City::create([ "id_departament"=>33, "name"=>"PUERTO CARREÑO"]);
        City::create([ "id_departament"=>33, "name"=>"SANTA ROSALIA"]);

    }
}
